version: ~> 1.0 # needed for imports

import: scala/scala-dev:travis/default.yml

language: scala

scala:
  - 0.22.0-RC1
  - 2.12.10
  - 2.13.1

env:
  - SCALAJS_VERSION=         ADOPTOPENJDK=8
  - SCALAJS_VERSION=0.6.32   ADOPTOPENJDK=8
  - SCALAJS_VERSION=1.0.1    ADOPTOPENJDK=8
  - SCALAJS_VERSION=         ADOPTOPENJDK=11
  - SCALAJS_VERSION=         ADOPTOPENJDK=13

matrix:
  exclude:
    - scala: 0.22.0-RC1
      env: SCALAJS_VERSION=0.6.32   ADOPTOPENJDK=8
    - scala: 0.22.0-RC1
      env: SCALAJS_VERSION=1.0.1    ADOPTOPENJDK=8

install:
  - git fetch --tags # get all tags for sbt-dynver

script: ./build.sh
