version: 2.1

executors:
  scala_jdk8_executor:
    docker:
      - image: circleci/openjdk:8-jdk-node
  scala_jdk11_executor:
    docker:
      - image: circleci/openjdk:11-jdk
  scala_jdk13_executor:
    docker:
      - image: circleci/openjdk:13.0.1-jdk-buster
  scala_jdk14_executor:
    docker:
      - image: circleci/openjdk:14-ea-26-jdk-buster

commands:
  sbt_cmd:
    description: "Build with sbt"
    parameters:
      scala_version:
        type: string
        default: 2.12.10
      sbt_tasks:
        type: string
        default: update compile test:compile test doc package
    steps:
      - restore_cache:
          keys:
            - sbt-deps-v1-{{ checksum "build.sbt" }}
            - sbt-deps-v1-
      - run: sbt ++<< parameters.scala_version >> << parameters.sbt_tasks >>
      - save_cache:
          key: sbt-deps-v1-{{ checksum "build.sbt" }}
          paths:
            - "~/.cache/coursier"
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

jobs:
  scala_job:
    executor: scala_<<parameters.java_version>>_executor
    parameters:
      scala_version:
        description: "Scala version"
        default: 2.12.10
        type: string
      java_version:
        description: "Java version"
        default: jdk8
        type: string
    steps:
      - checkout
      - run: java -version
      - sbt_cmd:
          scala_version: << parameters.scala_version >>
          sbt_tasks: xml/update xml/compile xml/test:compile xml/test xml/doc xml/package
  scalajs_job:
    executor: scala_jdk8_executor
    parameters:
      scala_version:
        description: "Scala version"
        default: 2.12.10
        type: string
      scalajs_version:
        description: "ScalaJS version"
        default: 0.6.32
        type: string
    environment:
      SCALAJS_VERSION: << parameters.scalajs_version >>
    steps:
      - checkout
      - run: java -version
      - run: node -v
      - sbt_cmd:
          scala_version: << parameters.scala_version >>
          sbt_tasks: xmlJS/update xmlJS/compile xmlJS/test:compile xmlJS/test xmlJS/doc xmlJS/package

workflows:
  build:
    jobs:
      - scala_job:
          name: 2.12.10
          java_version: jdk8
          scala_version: 2.12.10
      - scala_job:
          name: 2.13.1
          java_version: jdk8
          scala_version: 2.13.1
      - scala_job:
          name: dotty-0.22
          java_version: jdk8
          scala_version: 0.22.0-RC1
      - scala_job:
          name: jdk11_2.12
          java_version: jdk11
          scala_version: 2.12.10
      - scala_job:
          name: jdk11_2.13
          java_version: jdk11
          scala_version: 2.13.1
      - scala_job:
          name: jdk11_dotty
          java_version: jdk11
          scala_version: 0.22.0-RC1
      - scala_job:
          name: jdk13_2.12
          java_version: jdk13
          scala_version: 2.12.10
      - scala_job:
          name: jdk13_2.13
          java_version: jdk13
          scala_version: 2.13.1
      - scala_job:
          name: jdk13_dotty
          java_version: jdk13
          scala_version: 0.22.0-RC1
      - scala_job:
          name: jdk14_2.12
          java_version: jdk14
          scala_version: 2.12.10
      - scala_job:
          name: jdk14_2.13
          java_version: jdk14
          scala_version: 2.13.1
      - scala_job:
          name: jdk14_dotty
          java_version: jdk14
          scala_version: 0.22.0-RC1
      - scalajs_job:
          name: sjs0.6_2.12
          scala_version: 2.12.10
          scalajs_version: 0.6.32
      - scalajs_job:
          name: sjs0.6_2.13
          scala_version: 2.13.1
          scalajs_version: 0.6.32
      - scalajs_job:
          name: sjs1.0_2.12
          scala_version: 2.12.10
          scalajs_version: 1.0.1
      - scalajs_job:
          name: sjs1.0_2.13
          scala_version: 2.13.1
          scalajs_version: 1.0.1
